---
letsencrypt_gitlocation: /opt/letsencrypt

rsa_key_size: 2048
letsencrypt_server: https://acme-staging.api.letsencrypt.org/directory
standalone_supported_challenges: "tls-sni-01"
authenticator: "standalone"
webroot_path: ""
renew_days: 10
certificate_path: /etc/letsencrypt/live
